AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Fan out sample using AWS Lambda, SQS, SNS and Go
Parameters:
  WebhookURL:
    Type: String
  Channel:
    Type: String
  UserName:
    Type: String
  Icon:
    Type: String
  FileBucket:
    Type: String
    Default: sam-s3input-hisosi1900day00000
Resources:
  WriteExtLambda:
    Metadata:
      BuildMethod: go1.x
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: write_ext
      Handler: write_ext
      Runtime: provided.al2
      Timeout: 10
      Tracing: Active
      Architectures:
        - arm64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ForExtLambdaQueue.Arn
            BatchSize: 10
  WriteExtLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${WriteExtLambda}
      RetentionInDays: 1

  WriteFileNameLambda:
    Metadata:
      BuildMethod: go1.x
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: write_file_name
      Handler: write_file_name
      Runtime: provided.al2
      Timeout: 10
      Tracing: Active
      Architectures:
        - arm64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ForFileNameLambdaQueue.Arn
            BatchSize: 10
  WriteFileNameLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${WriteFileNameLambda}
      RetentionInDays: 1

  NotifierLambda:
    Metadata:
      BuildMethod: go1.x
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: notifier
      Handler: notifier
      Runtime: provided.al2
      Timeout: 10
      Tracing: Active
      Architectures:
        - arm64
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: S3FileTopic
      Environment:
        Variables:
          WEBHOOK_URL: !Ref WebhookURL
          CHANNEL: !Ref Channel
          USER_NAME: !Ref UserName
          ICON: !Ref Icon
  NotifierLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${NotifierLambda}
      RetentionInDays: 1

  S3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: SNSTopicPolicy
    Properties:
      BucketName: !Ref FileBucket
      NotificationConfiguration:
        TopicConfigurations:
        - Topic: !Ref S3FileTopic
          Event: s3:ObjectCreated:Put

  ForExtLambdaQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 20
      MessageRetentionPeriod: 60

  ForFileNameLambdaQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 20
      MessageRetentionPeriod: 60

  SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: "sns.amazonaws.com"
          Action: "sqs:SendMessage"
          Resource:
            - !GetAtt ForExtLambdaQueue.Arn
            - !GetAtt ForFileNameLambdaQueue.Arn
          Condition:
            StringEquals:
              aws:SourceArn:
              - !Ref S3FileTopic
      Queues:
      - !Ref ForExtLambdaQueue
      - !Ref ForFileNameLambdaQueue

  S3FileTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !GetAtt [ForExtLambdaQueue, Arn]
          Protocol: sqs
        - Endpoint: !GetAtt [ForFileNameLambdaQueue, Arn]
          Protocol: sqs
      TopicName: s3-file-topic
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref S3FileTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sns:Publish
            Resource: !Ref S3FileTopic
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::${FileBucket}"
            Principal:
              Service: "s3.amazonaws.com"
